# Designed for WT32-SC01 PLUS
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 16MB


# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216


# Over the Air Updates
ota:
- platform: esphome


# Enable Home Assistant API
api:


# Enable logging
logger:


# Packages
external_components:
  - source:
      type: git
      url: https://github.com/strange-v/ha_deck
      ref: main
    components: [ hd_device_sc01_plus, ha_deck ]


# Screen Brightness
hd_device_sc01_plus:
  id: device
  brightness: 100


psram:
    mode: octal
    speed: 80MHz
