substitutions:
  SCREEN_MAIN: master
  SCREEN_BLINDS: blinds

ha_deck:
  screens:
    - name: ${SCREEN_MAIN}
      widgets:

        # Time
        - type: value-card
          id: app1
          position: ${box1}
          text: Mail
          visible: |-
            return true;
          on_click:
            - homeassistant.service:
                service: switch.turn_on
                data:
                  entity_id: switch.office_3d_printer_power